# Generated by Django 3.1.5 on 2021-02-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
